
BOMBS = 3
MIN_AMOUNT_OF_POINTS_TO_PLAY = 21
END_GAME = 500
MAX_LIMIT_OF_BIDDING = 800
INCREASE_OF_BIDDING = 10
DEFAULT_BID = 100
POINTS_FROM_BOMB = 60

TIME_FOR_RELOAD_MOVE = 20

ACE = 6
TEN = 5
KING = 4
QUEEN = 3
JACK = 2
NINE = 1

HEART = 4       #kier
DIAMONDS = 3    #karo
CLUBS = 2       #trefl
SPADES = 1      #pik

HEART_POINTS = 100     #kier
DIAMONDS_POINTS = 80   #karo
CLUBS_POINTS = 60      #trefl
SPADES_POINTS = 40     #pik
